export const BRAND_ALIASES: Record<string, string[]> = {
  // ─── SNEAKERS / FOOTWEAR ──────────────────────────────────────────────────
  "Nike": ["nike", "NIKE", "Nike"],
  "Adidas": ["adidas", "Adidas", "ADIDAS"],
  "Jordan": ["Jordan", "Air Jordan", "air jordan"],
  "Yeezy": ["Yeezy", "yeezy"],
  "New Balance": ["New Balance", "new balance", "NB"],
  "Asics": ["asics", "ASICS", "Asics", "ASIcs", "ASIC", "ASIS", "ASICSTIGER"],
  "Converse": ["Converse"],
  "Vans": ["Vans"],
  "Puma": ["Puma"],
  "Reebok": ["Reebok"],
  "Salomon": ["Salomon"],
  "On Running": ["On Running", "ON Running", "ON RUNNING", "ON", "On", "on"],
  "Hoka": ["Hoka", "HOKA"],
  "Saucony": ["Saucony"],
  "Mizuno": ["Mizuno"],
  "Birkenstock": ["Birkenstock"],
  "Timberland": ["Timberland"],
  "UGG": ["UGG", "Ugg", "Uggs", "UGGS"],
  "Clarks": ["Clarks"],
  "Common Projects": ["Common Projects"],
  "Onitsuka Tiger": ["Onitsuka Tiger"],
  "Suicoke": ["Suicoke"],
  "Steve Madden": ["Steve Madden"],
  "Diadora": ["Diadora"],

  // ─── LUXURY ───────────────────────────────────────────────────────────────
  "Louis Vuitton": ["Louis Vuitton", "LV", "Lv", "Luis Vuitton", "Louis Vuiton", "Vuitton", "LOUIS VUITTON"],
  "Gucci": ["Gucci", "gucci", "GUCCI"],
  "Prada": ["Prada", "PRADA", "prada"],
  "Balenciaga": ["Balenciaga"],
  "Versace": ["Versace"],
  "Givenchy": ["Givenchy", "Givenchey"],
  "Valentino": ["Valentino", "VALENTINO", "Valentino Garavani"],
  "Bottega Veneta": ["Bottega Veneta", "Bottega"],
  "Saint Laurent": ["Saint Laurent", "YSL", "Yves Saint Laurent", "Yves Saint Laurent (YSL)"],
  "Celine": ["Celine", "CELINE"],
  "Loewe": ["Loewe", "LOEWE"],
  "Fendi": ["Fendi"],
  "Dior": ["Dior", "DIOR", "Christian Dior", "CHRISTIAN DIOR", "CD Dior", "Dior Homme"],
  "Chanel": ["Chanel", "CHANEL"],
  "Hermès": ["Hermes", "HERMES", "Hermès", "HERMÈS", "Hermés"],
  "Burberry": ["Burberry", "BURBERRY"],
  "Moncler": ["Moncler", "MONCLER"],
  "Tom Ford": ["Tom Ford", "TOM FORD"],
  "Alexander McQueen": ["Alexander McQueen", "McQueen"],
  "Vivienne Westwood": ["Vivienne Westwood"],
  "Dolce & Gabbana": ["Dolce & Gabbana", "Dolce Gabbana", "DOLCE&GABBANA", "D&G"],
  "Balmain": ["Balmain"],
  "Moschino": ["Moschino"],
  "Maison Margiela": ["Maison Margiela"],
  "Rick Owens": ["Rick Owens", "RICK OWENS DRKSHDW"],
  "Vetements": ["Vetements"],
  "Off-White": ["Off-White", "Off White", "OFF-WHITE", "OFF White", "OFF WHITE", "off-white"],
  "Amiri": ["Amiri", "AMIRI"],
  "Fear of God": ["Fear of God", "FEAR OF GOD", "Fear Of God", "FOG"],
  "Essentials": ["Essentials", "ESSENTIALS", "Fear of God Essentials", "Fear of God ESSENTIALS", "Essentials Fear of God", "FOG Essentials", "Essentials FOG", "Fear Of God Essentials", "Essetials"],
  "Casablanca": ["Casablanca", "CASABLANCA", "CasaBlanca", "Casa Blanca", "CASA BLANCA"],
  "Goyard": ["Goyard", "GOYARD"],
  "Loro Piana": ["Loro Piana"],
  "Brunello Cucinelli": ["Brunello Cucinelli", "Brunello Cuccinelli", "BRUNELLO CUCINELLI"],
  "Bulgari": ["Bulgari", "Bvlgari", "BVLGARI"],
  "Mulberry": ["Mulberry"],
  "Chloe": ["Chloe", "Chloé"],
  "Miu Miu": ["Miu Miu"],
  "Jacquemus": ["Jacquemus", "JACQUEMUS"],
  "Ami Paris": ["Ami Paris", "AMI"],
  "Acne Studios": ["Acne Studios"],
  "The Row": ["The Row"],
  "Marine Serre": ["Marine Serre"],
  "Jil Sander": ["Jil Sander"],
  "Comme des Garçons": ["Comme des Garçons"],
  "Nahmias": ["Nahmias"],
  "Kiko Kostadinov": ["Kiko Kostadinov"],
  "MCM": ["MCM"],
  "Berluti": ["Berluti"],
  "Ferragamo": ["Ferragamo", "Salvatore Ferragamo"],
  "Jimmy Choo": ["Jimmy Choo"],
  "Christian Louboutin": ["Christian Louboutin", "Louboutin"],
  "Manolo Blahnik": ["Manolo Blahnik"],
  "Tod's": ["Tod's"],
  "Polene": ["Polene"],
  "Longchamp": ["Longchamp"],
  "Rimowa": ["Rimowa", "RIMOWA"],
  "Lanvin": ["Lanvin", "LANVIN"],
  "Rhude": ["Rhude", "RHUDE"],
  "Bally": ["Bally"],
  "Maison Mihara Yasuhiro": ["Maison Mihara Yasuhiro"],
  "Maison Francis Kurkdjian": ["Maison Francis Kurkdjian", "Maison Francis", "MFK"],
  "Y/Project": ["Y/Project"],
  "Missoni": ["Missoni"],
  "Marc Jacobs": ["Marc Jacobs"],
  "Marcelo Burlon": ["Marcelo Burlon"],
  "Kjus": ["Kjus"],
  "Fusalp": ["Fusalp"],
  "Perfect Moment": ["Perfect Moment"],
  "Pyrenex": ["Pyrenex"],

  // ─── WATCHES / JEWELLERY ──────────────────────────────────────────────────
  "Rolex": ["Rolex", "Rolex "],
  "Audemars Piguet": ["Audemars Piguet"],
  "Patek Philippe": ["Patek Philippe", "Patek"],
  "Cartier": ["Cartier"],
  "Omega": ["Omega", "OMEGA"],
  "Hublot": ["Hublot"],
  "Tag Heuer": ["TAG Heuer", "Tag Heuer"],
  "IWC": ["IWC", "IWC Schaffhausen"],
  "Breitling": ["Breitling"],
  "Tudor": ["Tudor", "TUDOR"],
  "Seiko": ["Seiko"],
  "Longines": ["LONGINES", "Longines"],
  "Casio": ["Casio"],
  "Richard Mille": ["Richard Mille", "RICHARD MILLE"],
  "Jacob & Co": ["Jacob & Co"],
  "Vacheron Constantin": ["Vacheron Constantin"],
  "Van Cleef & Arpels": ["Van Cleef & Arpels", "Van Cleef"],
  "Tiffany & Co": ["Tiffany & Co", "Tiffany & co", "Tiffany & Co.", "Tiffany"],
  "Jaeger-LeCoultre": ["Jaeger-LeCoultre", "Jaeger LeCoultre", "JLC"],
  "F.P. Journe": ["F.P. Journe", "F.P. Journey", "F.P.Journe", "FP Journe", "FPJ"],
  "Blancpain": ["Blancpain"],
  "Breguet": ["Breguet"],
  "Piaget": ["Piaget"],
  "Panerai": ["Panerai"],
  "Ulysse Nardin": ["Ulysse Nardin"],
  "Chopard": ["Chopard"],
  "Zenith": ["Zenith"],
  "Swatch": ["Swatch"],
  "Franck Muller": ["Franck Muller"],
  "Girard-Perregaux": ["Girard-Perregaux"],
  "Parmigiani": ["Parmigiani"],
  "Carl F. Bucherer": ["Carl F. Bucherer"],

  // ─── STREETWEAR ───────────────────────────────────────────────────────────
  "Supreme": ["Supreme", "SUPREME"],
  "Palace": ["Palace"],
  "Stone Island": ["Stone Island"],
  "CP Company": ["CP Company", "C.P. Company", "C.P Company", "C.P."],
  "Stussy": ["Stussy"],
  "Bape": ["Bape", "BAPE", "A Bathing Ape", "Bathing Ape", "A Bathing Ape (BAPE)"],
  "Kith": ["Kith", "KITH"],
  "Trapstar": ["Trapstar", "TRAPSTAR"],
  "Corteiz": ["Corteiz", "Crtz", "crtz", "CRTZ", "Cortiez"],
  "Represent": ["Represent"],
  "Gallery Dept": ["Gallery Dept.", "Gallery Dept", "GALLERY DEPT.", "gallery dept", "gallery dept.", "GALLERT DEPT"],
  "Hellstar": ["Hellstar", "HELLSTAR", "Helstar", "HELSTAR"],
  "Nocta": ["NOCTA", "Nocta", "nocta"],
  "Chrome Hearts": ["Chrome Hearts"],
  "Sp5der": ["Sp5der", "SP5DER", "Spider", "sp5der"],
  "Eric Emanuel": ["Eric Emanuel", "ERIC EMANUEL"],
  "Denim Tears": ["Denim Tears", "DENIM TEARS"],
  "Palm Angels": ["Palm Angels"],
  "Travis Scott": ["Travis Scott", "TRAVIS SCOTT"],
  "Thrasher": ["Thrasher"],
  "True Religion": ["True Religion"],
  "Champion": ["Champion"],
  "Dsquared2": ["Dsquared", "DSQUARED2"],
  "Ed Hardy": ["Ed Hardy"],
  "Billionaire Boys Club": ["Billionaire Boys Club"],
  "Stray Rats": ["Stray Rats"],
  "Undefeated": ["Undefeated"],
  "Warren Lotas": ["Warren Lotas"],
  "Who Decides War": ["Who Decides War"],
  "Wacko Maria": ["Wacko Maria"],
  "Mastermind Japan": ["Mastermind Japan"],
  "Broken Planet": ["Broken Planet", "broken planet"],
  "Syna World": ["Syna World", "SYNA"],
  "Cole Buxton": ["Cole Buxton"],
  "Hoodrich": ["Hoodrich"],
  "Ganni": ["GANNI"],
  "Kapital": ["Kapital", "KAPITAL"],
  "Mitchell & Ness": ["Mitchell & Ness"],

  // ─── DESIGNER / CONTEMPORARY ──────────────────────────────────────────────
  "Ralph Lauren": ["Ralph Lauren", "RALPH LAUREN", "Polo Ralph Lauren", "POLO RALPH LAUREN", "Polo", "Ralf Lauren"],
  "Tommy Hilfiger": ["Tommy Hilfiger"],
  "Calvin Klein": ["Calvin Klein", "calvin klein"],
  "Hugo Boss": ["Hugo Boss", "BOSS"],
  "Lacoste": ["Lacoste"],
  "Fred Perry": ["Fred Perry"],
  "Paul Smith": ["Paul Smith"],
  "Ted Baker": ["Ted Baker"],
  "Barbour": ["Barbour"],
  "Belstaff": ["Belstaff"],
  "Armani": ["Armani", "Emporio Armani", "Giorgio Armani"],
  "Zegna": ["Zegna"],
  "Skims": ["Skims"],
  "Guess": ["Guess"],
  "AllSaints": ["AllSaints"],
  "Coach": ["Coach", "COACH"],
  "Ray-Ban": ["Ray-Ban", "Rayban"],
  "Juicy Couture": ["Juicy Couture"],
  "Karl Kani": ["Karl Kani"],

  // ─── SPORT / OUTDOOR ──────────────────────────────────────────────────────
  "Under Armour": ["Under Armour", "UNDERARMOUR", "UNDER ARMOUR"],
  "Lululemon": ["Lululemon", "lululemon"],
  "Castore": ["Castore"],
  "Montirex": ["Montirex"],
  "Alo Yoga": ["ALO Yoga", "Alo Yoga", "ALO", "Alo", "alo"],
  "Canada Goose": ["Canada Goose", "Canada goose"],
  "The North Face": ["The North Face"],
  "Arc'teryx": ["Arcteryx", "Arc'teryx"],
  "Patagonia": ["Patagonia"],
  "Berghaus": ["Berghaus", "BERGHAUS"],
  "Napapijri": ["Napapijri"],
  "Montane": ["Montane"],
  "Carhartt": ["Carhartt"],
  "Umbro": ["Umbro"],
  "RAB": ["RAB"],
  "K-Way": ["K-Way"],

  "Moose Knuckles": ["Moose Knuckles"],
  "Marshall Artist": ["Marshall Artist"],

  // ─── FRAGRANCE ────────────────────────────────────────────────────────────
  "Acqua di Parma": ["Acqua di Parma"],
  "Jo Malone": ["Jo Malone"],
  "Penhaligons": ["Penhaligons", "Penhaligon's"],
  "Creed": ["Creed"],
  "Jean Paul Gaultier": ["Jean Paul Gaultier"],

  // ─── HIGH STREET ──────────────────────────────────────────────────────────
  "Zara": ["Zara"],
  "H&M": ["H&M"],
  "Uniqlo": ["Uniqlo", "UNIQLO"],
  "Levi's": ["Levi's"],
};

export const BRAND_NAMES = Object.keys(BRAND_ALIASES);

export function resolveAliases(canonical: string): string[] {
  return BRAND_ALIASES[canonical] ?? [canonical.toLowerCase()];
}