export const BRAND_ALIASES: Record<string, string[]> = {
  // ─── LUXURY ───────────────────────────────────────────────
  "Louis Vuitton": ["lv", "louis vuitton", "louis vitton", "louie vuitton", "luis vuitton", "louis vuton", "lv bag", "lvmh"],
  "Gucci": ["gucci", "guccy", "guci"],
  "Prada": ["prada", "pradaa"],
  "Balenciaga": ["balenciaga", "balencaiga", "balenciagga", "balen", "balenci"],
  "Versace": ["versace", "versaci", "versayce"],
  "Givenchy": ["givenchy", "givency", "givenci"],
  "Valentino": ["valentino", "valantino"],
  "Bottega Veneta": ["bottega veneta", "bottega", "bv", "bottega venetta"],
  "Saint Laurent": ["saint laurent", "ysl", "yves saint laurent", "ysL", "saint laurant"],
  "Celine": ["celine", "céline", "celin"],
  "Loewe": ["loewe", "loewy", "loew"],
  "Fendi": ["fendi", "fendy"],
  "Dior": ["dior", "christian dior", "diorr"],
  "Chanel": ["chanel", "chanell", "chanel paris"],
  "Hermès": ["hermes", "hermès", "hèrmes", "herms", "birkin"],
  "Burberry": ["burberry", "burbury", "barbery", "burbs", "burberrys"],
  "Moncler": ["moncler", "monclair", "monclar"],
  "Tom Ford": ["tom ford", "tomford"],
  "Alexander McQueen": ["alexander mcqueen", "mcqueen", "mac queen", "alexander mcqueen"],
  "Vivienne Westwood": ["vivienne westwood", "vivienne", "westwood", "vw"],
  "Dolce & Gabbana": ["dolce and gabbana", "dolce & gabbana", "d&g", "dg", "dolce gabbana"],
  "Balmain": ["balmain", "balmaine"],
  "Moschino": ["moschino", "moshino"],
  "Marni": ["marni", "marnii"],
  "Acne Studios": ["acne studios", "acne", "acne studio"],
  "Maison Margiela": ["maison margiela", "margiela", "mm6", "martin margiela"],
  "Rick Owens": ["rick owens", "rick owen", "rickowens"],
  "Vetements": ["vetements", "vetment", "vetements"],
  "Off-White": ["off-white", "off white", "offwhite", "off wite"],
  "A-Cold-Wall": ["a-cold-wall", "a cold wall", "acw", "acoldwall"],
  "Palm Angels": ["palm angels", "palm angel"],
  "Amiri": ["amiri", "amirii"],
  "Fear of God": ["fear of god", "fog", "fear of god essentials"],
  "Essentials": ["essentials", "fog essentials", "fear of god essentials"],

  // ─── STREETWEAR ───────────────────────────────────────────
  "Supreme": ["supreme", "suprème", "sup", "supremee"],
  "Palace": ["palace", "palace skateboards", "plc"],
  "Stone Island": ["stone island", "stone isl", "si", "stoney", "stone"],
  "CP Company": ["cp company", "c.p. company", "cp", "c.p company"],
  "Stussy": ["stussy", "stüssy", "stussi", "stussyy"],
  "Bape": ["bape", "a bathing ape", "bathing ape", "a bathing ape"],
  "Kith": ["kith", "kithh"],
  "Anti Social Social Club": ["anti social social club", "assc", "antisocial social club"],
  "Human Made": ["human made", "humanmade"],
  "Undercover": ["undercover", "undercoverism"],
  "Neighborhood": ["neighborhood", "nbhd", "neighbourhood"],
  "Wtaps": ["wtaps", "w-taps", "doubletaps"],
  "Aimé Leon Dore": ["aimé leon dore", "aime leon dore", "ald"],
  "Carhartt WIP": ["carhartt wip", "carhartt", "carhatt", "carhart"],
  "Dickies": ["dickies", "dicky"],
  "Trapstar": ["trapstar", "trap star"],
  "Corteiz": ["corteiz", "crtz", "cortez clothing"],
  "Represent": ["represent", "represent clo", "represent clothing"],
  "Daily Paper": ["daily paper", "dailypaper"],
  "Filling Pieces": ["filling pieces", "fillingpieces"],
  "Maharishi": ["maharishi", "maha"],
  "Acronym": ["acronym", "acrnm"],

  // ─── SNEAKERS / FOOTWEAR ──────────────────────────────────
  "Nike": ["nike", "niike", "nik", "swoosh"],
  "Adidas": ["adidas", "addidas", "adidass", "adi", "three stripes"],
  "Jordan": ["jordan", "air jordan", "aj", "jordans"],
  "Yeezy": ["yeezy", "yeezys", "yzy", "yeezi", "adidas yeezy"],
  "New Balance": ["new balance", "nb", "new ballance", "newbalance"],
  "Asics": ["asics", "asic", "assics", "asics gel"],
  "Saucony": ["saucony", "sauconny", "sauconey"],
  "Converse": ["converse", "convers", "chuck taylor", "chucks"],
  "Vans": ["vans", "van shoes"],
  "Puma": ["puma", "pumaa"],
  "Reebok": ["reebok", "rebok", "reebock"],
  "Salomon": ["salomon", "solomon shoes", "salamon"],
  "On Running": ["on running", "on cloud", "on", "on cloudrunner"],
  "Hoka": ["hoka", "hoka one one", "hokaoneone"],
  "Brooks": ["brooks", "brooks running"],
  "Mizuno": ["mizuno", "mizunoo"],
  "Merrell": ["merrell", "merell"],
  "Timberland": ["timberland", "timbs", "timbos", "timberlands"],
  "Dr Martens": ["dr martens", "dr. martens", "docs", "dms", "doc martens"],
  "Clarks": ["clarks", "clark shoes"],
  "UGG": ["ugg", "uggs", "ugg boots"],
  "Birkenstock": ["birkenstock", "birks", "birkenstocks"],
  "Common Projects": ["common projects", "cp", "common project"],

  // ─── SPORTS / PERFORMANCE ─────────────────────────────────
  "Under Armour": ["under armour", "under armor", "ua", "underarmour"],
  "Lululemon": ["lululemon", "lulu", "lululemmon"],
  "Gymshark": ["gymshark", "gym shark"],
  "Castore": ["castore", "castorre"],
  "Montirex": ["montirex", "montrex"],
  "Ellesse": ["ellesse", "elles", "elesse"],
  "Fila": ["fila", "filla"],
  "Kappa": ["kappa", "kapa"],
  "Umbro": ["umbro", "ombro"],
  "Hummel": ["hummel", "humel"],

  // ─── DESIGNER / CONTEMPORARY ──────────────────────────────
  "Ralph Lauren": ["ralph lauren", "ralph", "polo ralph lauren", "polo", "rl", "polo rl"],
  "Tommy Hilfiger": ["tommy hilfiger", "tommy", "hilfiger", "tommy hil"],
  "Calvin Klein": ["calvin klein", "ck", "calvinklein"],
  "Hugo Boss": ["hugo boss", "boss", "hugo"],
  "Lacoste": ["lacoste", "lacost", "lacoste polo"],
  "Fred Perry": ["fred perry", "fred", "fp"],
  "Hackett": ["hackett", "hacket"],
  "Paul Smith": ["paul smith", "paulsmith"],
  "Ted Baker": ["ted baker", "ted"],
  "Reiss": ["reiss", "riess"],
  "AllSaints": ["allsaints", "all saints"],
  "Belstaff": ["belstaff", "belstaf"],
  "Barbour": ["barbour", "barber jacket", "barbour jacket"],
  "Mackintosh": ["mackintosh", "mackintosh london"],
  "Sunspel": ["sunspel", "sun spel"],

  // ─── WORKWEAR / CASUAL ────────────────────────────────────
  "Levi's": ["levis", "levi's", "levi strauss", "levis jeans"],
  "Wrangler": ["wrangler", "wrangler jeans"],
  "Lee": ["lee jeans", "lee denim"],
  "Nudie Jeans": ["nudie jeans", "nudie", "nudiejeans"],
  "G-Star RAW": ["g-star raw", "g star raw", "gstar", "g-star"],
  "Diesel": ["diesel", "diesel jeans"],
  "Edwin": ["edwin", "edwin jeans"],

  // ─── OUTDOOR / TECHNICAL ──────────────────────────────────
  "The North Face": ["the north face", "tnf", "north face", "northface"],
  "Arc'teryx": ["arcteryx", "arc'teryx", "arc teryx", "arcterex"],
  "Patagonia": ["patagonia", "patgonia", "patagona"],
  "Columbia": ["columbia", "columbia sportswear"],
  "Berghaus": ["berghaus", "berg haus"],
  "Napapijri": ["napapijri", "napa", "napapijiri"],
  "Mammut": ["mammut", "mamut"],
  "Montane": ["montane", "montan"],
  "Fjallraven": ["fjallraven", "fjäll räven", "kanken", "fjallraven kanken"],
  "Rab": ["rab", "rab outdoor"],
  "Haglofs": ["haglofs", "haglöfs"],

  // ─── HIGH STREET ──────────────────────────────────────────
  "Zara": ["zara", "zaraa"],
  "H&M": ["h&m", "hm", "h and m"],
  "ASOS": ["asos", "asos design"],
  "Topman": ["topman", "top man"],
  "Cos": ["cos", "cos clothing"],
  "Uniqlo": ["uniqlo", "uniqloe", "uniqloo"],
  "Arket": ["arket"],
  "& Other Stories": ["& other stories", "other stories"],
  "Weekday": ["weekday"],
  "Monki": ["monki"],
};

export const BRAND_NAMES = Object.keys(BRAND_ALIASES);

export function resolveAliases(canonical: string): string[] {
  return BRAND_ALIASES[canonical] ?? [canonical.toLowerCase()];
}